# Generated by Django 5.2.3 on 2025-06-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=200)),
                ('autori', models.CharField(max_length=100)),
                ('viti_publikimit', models.IntegerField()),
            ],
        ),
    ]
